#!/bin/bash
# republish-ep3-v2.sh
# One-shot script to republish Episode 3 ("Salt", v2) after audio has been
# regenerated by generate-audio-v3.py.
#
# What this does:
#   1. Confirms the new audio file exists in audio/the-future-economy/
#   2. Copies it to audio/ with the -v2 suffix (new filename, new GUID)
#   3. Removes the old ep003 item from feed.xml
#   4. Inserts the new ep003-v2 item at the top of the items list
#   5. Git commits and pushes (so GitHub Pages serves the new audio)
#
# Usage (from Windows Git Bash, or any bash environment with git access):
#   cd ~/CODE/ironline-podcast
#   python engine/scripts/generate-audio-v3.py the-future-economy 3   # regenerates audio
#   bash engine/scripts/republish-ep3-v2.sh                            # publishes the swap

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

EPISODE_DIR="$PROJECT_ROOT/series/the-future-economy/episodes/ep003"
AUDIO_META="$EPISODE_DIR/audio-metadata.json"
FEED_FILE="$PROJECT_ROOT/feed.xml"

if [ ! -f "$AUDIO_META" ]; then
    echo "ERROR: $AUDIO_META not found. Did generate-audio-v3.py finish?"
    exit 1
fi

# Read the latest audio file path from audio-metadata.json
AUDIO_SOURCE=$(python3 -c "import json; print(json.load(open('$AUDIO_META'))['audio_file'])")
if [ ! -f "$AUDIO_SOURCE" ]; then
    echo "ERROR: audio file referenced in metadata not found: $AUDIO_SOURCE"
    exit 1
fi

# Sanity check: the audio file must have been generated TODAY, otherwise
# we're about to republish stale audio.
TODAY=$(date +%Y-%m-%d)
if ! basename "$AUDIO_SOURCE" | grep -q "^${TODAY}_ep003"; then
    echo "WARNING: audio file is not dated today ($TODAY)."
    echo "         filename: $(basename "$AUDIO_SOURCE")"
    read -p "Proceed anyway? [y/N] " confirm
    [[ "$confirm" =~ ^[Yy]$ ]] || exit 1
fi

# Destination filename: use -v2 suffix so Spotify and other podcast apps
# treat it as a new episode rather than caching the old one.
NEW_FILENAME="the-future-economy-ep003-v2.mp3"
NEW_DEST="$PROJECT_ROOT/audio/$NEW_FILENAME"

cp "$AUDIO_SOURCE" "$NEW_DEST"
FILE_SIZE=$(stat -f%z "$NEW_DEST" 2>/dev/null || stat --printf="%s" "$NEW_DEST" 2>/dev/null)
echo "Copied audio: $NEW_DEST ($FILE_SIZE bytes)"

# Build the new RSS item.
NEW_GUID="the-future-economy-ep003-v2"
NEW_TITLE="The Future Economy — Salt"
NEW_AUDIO_URL="https://eggmcmark.github.io/ironline-podcast/audio/$NEW_FILENAME"
PUB_DATE=$(date -u "+%a, %d %b %Y %H:%M:%S +0000")

# Description pulled from metadata.json summary.
SUMMARY=$(python3 -c "
import json
m = json.load(open('$EPISODE_DIR/metadata.json'))
print(m.get('summary', ''))
")

NEW_ITEM=$(cat <<EOF
    <item>
      <title>$NEW_TITLE</title>
      <description><![CDATA[$SUMMARY]]></description>
      <pubDate>$PUB_DATE</pubDate>
      <enclosure url="$NEW_AUDIO_URL" type="audio/mpeg" length="$FILE_SIZE" />
      <itunes:episode>3</itunes:episode>
      <itunes:season>1</itunes:season>
      <itunes:duration>40:00</itunes:duration>
      <itunes:explicit>no</itunes:explicit>
      <itunes:episodeType>full</itunes:episodeType>
      <guid isPermaLink="false">$NEW_GUID</guid>
    </item>
EOF
)

# Update feed.xml: remove the old ep003 item (GUID the-future-economy-ep003)
# and insert the new item at the top of the items list.
python3 << PYEOF
import re
from pathlib import Path

feed_path = Path("$FEED_FILE")
new_item = """$NEW_ITEM"""

text = feed_path.read_text(encoding="utf-8")

# Remove the old ep003 item by its GUID.
old_pattern = re.compile(
    r'    <item>\s*'
    r'(?:(?!<item>).)*?'
    r'<guid[^>]*>the-future-economy-ep003</guid>\s*'
    r'</item>\s*',
    re.DOTALL
)
new_text, n_removed = old_pattern.subn('', text)
if n_removed:
    print(f"Removed {n_removed} old ep003 item(s) from feed.xml")
else:
    print("No existing ep003 item found in feed.xml (already clean).")

# Insert the new item before the first existing <item>.
def insert_before_first_item(s, item):
    idx = s.find('    <item>')
    if idx < 0:
        # No items yet — insert before </channel>
        idx = s.find('  </channel>')
    return s[:idx] + item + '\n' + s[idx:]

new_text = insert_before_first_item(new_text, new_item)
feed_path.write_text(new_text, encoding="utf-8")
print("Inserted new ep003-v2 item at top of feed.xml")
PYEOF

echo ""
echo "=== Feed updated ==="
echo "  New GUID:     $NEW_GUID"
echo "  New filename: $NEW_FILENAME"
echo "  New URL:      $NEW_AUDIO_URL"

# Git commit and push.
cd "$PROJECT_ROOT"
git add feed.xml audio/$NEW_FILENAME series/the-future-economy/
git commit -m "Republish: The Future Economy S1E03 — Salt (v2 rewrite)

Supersedes the original 'The Frontier' (ep003 v1, GUID the-future-economy-ep003)
with a new script and audio file (GUID the-future-economy-ep003-v2). Old
GUID is removed from feed.xml so podcast clients pull the v2 as a fresh
episode rather than caching the v1."

git push origin main

echo ""
echo "=== Done ==="
echo "Spotify and other podcast clients will pick up the new episode on their"
echo "next feed refresh (usually within an hour for Spotify)."
