#!/bin/bash
# setup-weekly-cron.sh — Create a Windows Scheduled Task for weekly episode generation
# Run this once to set up the recurring job.
#
# The task runs every Thursday at 3:00 AM (configurable below)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Configuration
TASK_NAME="IronlinePodcastEngine"
SERIES_SLUG="${1:-the-future-economy}"
DAY_OF_WEEK="THU"     # MON, TUE, WED, THU, FRI, SAT, SUN
TIME="03:00"           # 24-hour format
BASH_PATH="${BASH_PATH:-$(which bash)}"

# Convert project root to Windows path for Task Scheduler
WIN_PROJECT_ROOT=$(cygpath -w "$PROJECT_ROOT" 2>/dev/null || echo "$PROJECT_ROOT" | sed 's|/c/|C:\\|; s|/|\\|g')

echo "=== Setting up Weekly Podcast Cron ==="
echo "  Task Name: $TASK_NAME"
echo "  Series: $SERIES_SLUG"
echo "  Schedule: Every $DAY_OF_WEEK at $TIME"
echo "  Project: $WIN_PROJECT_ROOT"
echo ""

# Create a wrapper batch file that Task Scheduler can execute
BATCH_FILE="$PROJECT_ROOT/engine/run-weekly.bat"
cat > "$BATCH_FILE" << BATCH_EOF
@echo off
REM Ironline Podcast Engine — Weekly Episode Generation
REM Auto-generated by setup-weekly-cron.sh

cd /d "$WIN_PROJECT_ROOT"

REM Run the orchestrator via Git Bash
"$BASH_PATH" -l -c "cd '$PROJECT_ROOT' && ./engine/orchestrate.sh $SERIES_SLUG" >> "$PROJECT_ROOT\\engine\\logs\\scheduled_run.log" 2>&1
BATCH_EOF

echo "Created batch wrapper: $BATCH_FILE"

# Create the Windows Scheduled Task via schtasks
echo ""
echo "To create the Windows Scheduled Task, run this command in an elevated (Admin) PowerShell:"
echo ""
echo "  schtasks /create /tn \"$TASK_NAME\" /tr \"$(cygpath -w "$BATCH_FILE" 2>/dev/null || echo "$BATCH_FILE" | sed 's|/c/|C:\\|; s|/|\\|g')\" /sc weekly /d $DAY_OF_WEEK /st $TIME /rl highest /f"
echo ""
echo "To verify: schtasks /query /tn \"$TASK_NAME\" /v"
echo "To run now: schtasks /run /tn \"$TASK_NAME\""
echo "To delete:  schtasks /delete /tn \"$TASK_NAME\" /f"
echo ""
echo "Alternatively, use Task Scheduler GUI (taskschd.msc) to customize further."
